version: '3.8'
services:
  
  worker:
    build:
      context: src
      dockerfile: background-worker/PdfGenerator.Worker/Dockerfile
    container_name: background-worker
    depends_on: 
      - postgres
      - minio
    networks:
      - pdf-generator
  
  web-server:
    build:
      context: src
      dockerfile: web-server/PdfGenerator.WebApi/Dockerfile
    container_name: web-server
    depends_on:
      - postgres
      - minio
      - worker
    networks:
      - pdf-generator
  
  postgres:
    image: postgres:latest
    container_name: pg-database
    networks:
      - pdf-generator
    environment:
      POSTGRES_DB: pdf_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - pdf-generator
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server /data
    ports:
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  pg-data:
  minio-data:

networks:
  pdf-generator:
    driver: bridge